set ::env(PDK) "sky130A"
set ::env(PDKPATH) "/home/kitti/OpenLane/pdks/sky130A"
set ::env(STD_CELL_LIBRARY) "sky130_fd_sc_hd"
set ::env(SCLPATH) "/home/kitti/OpenLane/pdks/sky130A/sky130_fd_sc_hd"
set ::env(DESIGN_DIR) "/openlane/designs/FIR_p"
set ::env(DESIGN_NAME) "FIR_Lowpass_Filter"
set ::env(VERILOG_FILES) "designs/FIR_p/src/FIR_Lowpass_Filter.v"
set ::env(CLOCK_PORT) "clk"
set ::env(CLOCK_PERIOD) "10.0"
set ::env(DIE_AREA) "0 0 500 500"
set ::env(PL_TARGET_DENSITY) "0.4"
set ::env(FP_CORE_UTIL) "30"
set ::env(ROUTING_CORES) "4"
set ::env(SYNTH_STRATEGY) "DELAY 1"
set ::env(SYNTH_MAX_FANOUT) "5"
set ::env(FP_PIN_ORDER_CFG) "designs/FIR_p/pin_order.cfg"
